### ISSUE TITLE
Calendar re-design

### ISSUE THREAD

**Issue by kennyvn** [Sharebold/issues#14]
http://prntscr.com/ka6iyo

**Comment by luongvm** [comment]
working on it after got design

**Comment by luongvm** [comment]
deployed, search and jump added

**Comment by phuongdesigner** [comment]
Calendar enhancements: @joturako 

- [ ] Thêm loading skeleton khi load dữ liệu trên lịch.

- [ ] Thêm dấu "..." sau content, cắt theo dòng chữ để không bị lẻ chữ cái vô nghĩa.

**Comment by luongvm** [comment]
ok :) done again plz check
