### ISSUE TITLE
Thay đổi flow tạo Team 

### ISSUE THREAD

**Issue by kennyvn** [Sharebold/issues#2]
Sau khi tạo Team, chỉ suggest tạo profile chứ không bắt buộc

**Comment by phuongdesigner** [comment]
@joturako zpl://screen?sid=5b19f858a1cfc2e506cd06cb&pid=5b025410d3f42d5872ec84cd
zpl://screen?sid=5b19f856b04866f722d8c562&pid=5b025410d3f42d5872ec84cd

Check zeplin nhé

**Comment by luongvm** [comment]
@nvvu u want?

**Comment by luongvm** [comment]
done :)
