### ISSUE TITLE
[Account setting] Thêm ảnh avatar mặc định khi user chưa có avatar

### ISSUE THREAD

**Issue by phuongdesigner** [Sharebold/issues#24]
Thêm ảnh avatar mặc định khi user chưa có avatar
https://tppr.me/zjvvr

Tải avatar mặc định trên zeplin:
zpl://screen?sid=5b4c2580fd1c860530da7901&pid=5b025410d3f42d5872ec84cd

**Comment by nvvu** [comment]
Done.
