### ISSUE TITLE
[Account setting] upload ảnh avatar bị méo

### ISSUE THREAD

**Issue by phuongdesigner** [Sharebold/issues#32]
- [ ] Upload ảnh avatar bị méo

- [ ] Thêm trang thái loading trên ảnh khi đang upload avatar

**Comment by nvvu** [comment]
Fixed.

**Comment by phuongdesigner** [comment]
@nvvu Em align lại phần Avatar nó align left để cân đối nhé. https://tppr.me/cMUeC
Check lại thêm https://zpl.io/VDzexre nhé

**Comment by phuongdesigner** [comment]
@nvvu Thêm trạng thái disconnect Social em nhé. A có tag em trên Zeplin phần đó.

**Comment by phuongdesigner** [comment]
Chỉnh padding top tăng lên và padding right nhỏ lại e nhé @nvvu 
![image](https://user-images.githubusercontent.com/41603390/43434630-b39027ce-94a6-11e8-9337-dc44c15605fa.png)
