### ISSUE TITLE
Xây dựng phần quản lý cho role QC, duyệt lại post idea trước khi publish 

### ISSUE THREAD

**Issue by kennyvn** [Sharebold/issues#37]
- Hỗ trợ tìm kiếm, chuyển trạng thái, chỉnh sửa post idea 
- Hỗ trợ filter post idea theo keywords & content 
   + No keyword 
   + Less than 10 keywords 
   + Long form ( > 255 characters ) 
   + Less form ( <= 255 characters ) 
- Date time created

**Comment by nvvu** [comment]
Done
